name: SocietyCraft
main: thisisboris.SocietyCraft.SocietyCraft
version: 0.0.1

commands:
    SocietyCraft:
        description: Basic command to access help
        usage: |
    SC:
    	description: Basic command to acces help, short version
    	usage: |
    SocietyAdmin:
        description: Societycraft admin commands.
        usage: |
    SA:
    	description: Societycraft admin commands, short version