name: SocietyCraft
main: thisisboris.SocietyCraft.SocietyCraft
version: 0.0.1
authors: cskiwi, thisisboris
description: After a couple of months of hosting a bukkit server, we decided to create our very own plugin, based upon the way we play minecraft.
softdepend: iConomy, Permissions

commands:
    SocietyCraft:
        description: Basic command to access help
        usage: |
          /<command>
          Example: /<command> : Shows the basic help page.
          Example: /<command> Settlement : Shows the settlement help page.
    SC:
    	description: Basic command to acces help, short version
    	usage: |
          /<command>
          Example: /<command> : Shows the basic help page.
          Example: /<command> Settlement : Shows the settlement help page.
    SocietyAdmin:
        description: Societycraft admin commands.
        usage: |
          /<command>
          Example: /<command> : Shows the admin page with statistics etc.
          Example: /<command> Settlement : Shows the settlement admin page.
    SA:
    	description: Societycraft admin commands, short version
    	usage: |
          /<command>
          Example: /<command> : Shows the admin page with statistics etc.
          Example: /<command> Settlement : Shows the settlement admin page.
